
    create table bici (
        id integer not null,
        id_freno integer not null,
        id_sospensione integer not null,
        nr_ruote integer not null,
        numero_marce integer not null,
        pieghevole boolean not null,
        primary key (id)
    );

    create table categoria (
        id integer generated by default as identity,
        descrizione varchar(255) not null,
        tipo_veicolo varchar(255) not null,
        primary key (id)
    );

    create table macchina (
        cc integer not null,
        id integer not null,
        nr_ruote integer not null,
        numero_porte integer not null,
        primary key (id)
    );

    create table messagi_sistema (
        lang varchar(4) not null,
        code varchar(20) not null,
        messagio varchar(255),
        primary key (lang, code)
    );

    create table moto (
        cc integer not null,
        id integer not null,
        nr_ruote integer not null,
        primary key (id)
    );

    create table targa (
        id integer generated by default as identity,
        id_macchina integer unique,
        id_moto integer unique,
        codice varchar(255) not null unique,
        primary key (id)
    );

    create table tipo_alimentazione (
        id integer generated by default as identity,
        descrizione varchar(255) not null,
        tipo_veicolo varchar(255) not null,
        primary key (id)
    );

    create table tipo_freno (
        id integer generated by default as identity,
        descrizione varchar(255) not null,
        primary key (id)
    );

    create table tipo_sospensione (
        id integer generated by default as identity,
        descrizione varchar(255) not null,
        primary key (id)
    );

    create table veicoli (
        anno_produzione integer not null,
        id integer generated by default as identity,
        id_alimentazione integer not null,
        id_categoria integer not null,
        tipo_veicolo varchar(31) not null check ((tipo_veicolo in ('Veicoli','BICI','MACCHINA','MOTO'))),
        colore varchar(255) not null,
        marca varchar(255) not null,
        modello varchar(255) not null,
        primary key (id)
    );

    alter table if exists bici 
       add constraint FKiv6w39rnjduocl17c8dhoqoh4 
       foreign key (id_freno) 
       references tipo_freno;

    alter table if exists bici 
       add constraint FK728jkilwcanp13x491m4pgc4f 
       foreign key (id_sospensione) 
       references tipo_sospensione;

    alter table if exists bici 
       add constraint FKra4pq79y6t94qnygjmhto1d2f 
       foreign key (id) 
       references veicoli;

    alter table if exists macchina 
       add constraint FKlinll7qwn6u0njwsg3l9la5ue 
       foreign key (id) 
       references veicoli;

    alter table if exists moto 
       add constraint FKt01inn1jct6p6irfuar0pt15d 
       foreign key (id) 
       references veicoli;

    alter table if exists targa 
       add constraint FK3tdctv8wi569qk18vupvja5va 
       foreign key (id_macchina) 
       references macchina;

    alter table if exists targa 
       add constraint FKqi8hmjvp97d07m030a351o6pk 
       foreign key (id_moto) 
       references moto;

    alter table if exists veicoli 
       add constraint FKvoxq1l514latwhn6xi35cnm4 
       foreign key (id_categoria) 
       references categoria;

    alter table if exists veicoli 
       add constraint FK493ennwvu9uona9a1xcl00j6v 
       foreign key (id_alimentazione) 
       references tipo_alimentazione;
