
    create table veicoli (
        anno_p integer not null,
        id integer generated by default as identity,
        tipo_veicolo varchar(31) not null check ((tipo_veicolo in ('Veicoli'))),
        colore varchar(255) not null,
        marca varchar(255) not null,
        modello varchar(255) not null,
        primary key (id)
    );
