search.query=SELECT v FROM Veicoli v \
	LEFT JOIN TREAT(v AS Macchina) mc \
	LEFT JOIN TREAT(v AS Moto) mo \
	LEFT JOIN TREAT(v AS Bici) b \
	WHERE (:tipoVeicolo IS NULL OR v.tipoVeicolo = :tipoVeicolo) \
	AND (:marca IS NULL OR LOWER(v.marca) LIKE LOWER(CONCAT('%', :marca, '%'))) \
	AND (:modello IS NULL OR LOWER(v.modello) LIKE LOWER(CONCAT('%', :modello, '%'))) \
	AND (:colore IS NULL OR v.colore = :colore) \
	AND (:annoProduzione IS NULL OR v.annoProduzione = :annoProduzione) \
	AND (:tipoAlimentazione IS NULL OR v.tipoAlimentazione.descrizione = :tipoAlimentazione) \
	AND (:categoria IS NULL OR v.categoria.descrizione = :categoria) \
	AND (:targa IS NULL OR mc.targa.codice = :targa OR mo.targa.codice = :targa)