search.query=SELECT v FROM Veicoli v \
	LEFT JOIN Macchina mc ON mc.id = v.id \
	LEFT JOIN Moto mo ON mo.id = v.id \
	LEFT JOIN Bici b ON b.id = v.id \
	LEFT JOIN Targa tmc ON tmc.macchina = mc \
	LEFT JOIN Targa tmo ON tmo.moto = mo \
	WHERE (:tipoVeicolo IS NULL OR v.tipoVeicolo = :tipoVeicolo) \
	AND (:marca IS NULL OR LOWER(v.marca) LIKE LOWER(CONCAT('%', CAST(:marca AS text), '%'))) \
	AND (:modello IS NULL OR LOWER(v.modello) LIKE LOWER(CONCAT('%', CAST(:modello AS text), '%'))) \
	AND (:colore IS NULL OR v.colore = :colore) \
	AND (:annoProduzione IS NULL OR v.annoProduzione = :annoProduzione) \
	AND (:tipoAlimentazione IS NULL OR v.tipoAlimentazione.descrizione = :tipoAlimentazione) \
	AND (:categoria IS NULL OR v.categoria.descrizione = :categoria) \
	AND (:targa IS NULL OR tmc.codice = :targa OR tmo.codice = :targa)